# Site settings
title: "HI-ARC"
fulltitle: "홍익대학교 알고리즘 학회<br>HI-ARC 공식블로그"
tagline: ""
url: "http://hi-arc.github.io" # The base hostname & protocol for your site. Use it if you need absolute URL's

color-theme: "pink"

# Social
socialimg: /img/HIARC_social.jpg # be sure to change this image
facebook: "hongikuniv.hiarc"
twitter: twusername
github: "HI-ARC"
googleplus: gusername
instagram: igusername

# Contact
phone: "010-6375-7524"          # 대외 연락 담당자 전화번호
email: "hiarc.official@gmail.com" # 대외 연락 담당자 이메일

# Apply
apply-form: "https://forms.gle/RuGoexsbVNaqsrDP8"
newbie-apply-form: "https://forms.gle/jwTAFjgggzA3Hqr88"
apply-date: "신입생, 재학생 모두 2020년 3월 21일까지"
joinable: true

# Category
collections:
  sections:
    output: false

  lists:
    output: false


# Use this for production
#sass:
#  style: compressed

exclude: [.scss, .gitignore, .travis.ci, Gemfile, Gemfile.lock, README.md, node_modules, gruntfile.js, package.json]
